spring:
  application:
    name: ai-agent
  profiles:
    active: local
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3.5:4b
#    mcp:
#      client:
#        stdio:
#          servers-configuration: classpath:mcp-servers.json

    mcp:
      client:
        request-timeout: 60000   # 60秒，默认20秒
        sse:
          connections:
            server1:
              url: http://localhost:8127
        # stdio:
        # servers-configuration: classpath:mcp-servers.json

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi 接口文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.iverson.aiagent.controller
# knife4j 的争强配置，不需要可以不添加
knife4j:
  enable: true
  setting:
    language: zh_cn


