spring:
  application:
    name: ai-agent
  ai:
    dashscope:
      api-key: sk-51a34bf7b4864845aa06832ce67e2cd5
      chat:
        options:
          model: qwen-plus
#    vectorstore:
#      pgvector:
#        index-type: HNSW
#        dimensions: 1536
#        distance-type: COSINE_DISTANCE
#        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
  datasource:
    url: jdbc:mysql://localhost:3306/ai_llm?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 199812abC.
    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:postgresql://rm-cn-2684pl3mx000157o.rwlb.rds.aliyuncs.com:5432/yu_ai_agant
#    username: my_user
#    password: 199812abC_

# searchApi
search-api:
  api-key: MkPen6f1uvqSojJvqj5Q59CL

