spring:
  ai:
    mcp:
      server:
        name: image-search-mcp
        version: 0.0.1
        type: SYNC
        # sse
        stdio: false
  application:
    name: image-search-mcp
  profiles:
    active: sse
server:
  port: 8127
